### ISSUE TITLE
Support for API 16

### ISSUE THREAD

**Issue by sajorahasan** [sdsmdg/RotatingText#1]
Hello, thanks for this great library but don't you think minimum Api level 19 is too high.
If its possible can you please bring it down to Api 16.
Thank you

**Comment by harjot-oberai** [comment]
Done 👍 
I don't have an API 16 device, so can you please verify that it works on an API 16 device, so that I may close this issue.

**Comment by sajorahasan** [comment]
Hello,

Thank you very much, give me 10-20 min. I will report back to you

**Comment by sajorahasan** [comment]
Great ! 
Its working fine on Api 16
I have tested it on Genymotion Google Nexus model.
